### ISSUE TITLE
Release version that follows semantic version format

### ISSUE THREAD

**Issue by floitsch** [ojmason/toit-csv#2]
This package is currently released as v1.0.

Toit is moving towards accepting only "complete" version numbers (like v1.0.0).
Please release a new version (could be the same code) with a complete version number.

**Comment by floitsch** [comment]
I created https://github.com/ojmason/toit-csv/pull/1 to incentivize a new release.

**Comment by ojmason** [comment]
OK, I think I have now created a new release.

**Comment by floitsch** [comment]
thanks!
